import 'package:the_exchange_app/models/currencies.dart';

List<CountryCurrency> kCountriesCurrenciesList = [
  CountryCurrency(
    countryISOCode: "us",
    countryName: "United States",
    currencyISOCode: "usd",
    currencyName: "US dollar",
    region: "Main",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar estadounidense',
    pais: 'Estados Unidos',
    zona: 'Main',
  ),
  CountryCurrency(
    countryISOCode: "eu",
    countryName: "Europe",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Main",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Europa',
    zona: 'Main',
  ),
  CountryCurrency(
    countryISOCode: "ca",
    countryName: "Canada",
    currencyISOCode: "cad",
    currencyName: "Canadian dollar",
    region: "Main",
    isChecked: false,
    firstItem: true,
    moneda: 'Dólar canadiense',
    pais: 'Canada',
    zona: 'Main',
  ),
  CountryCurrency(
    countryISOCode: "gb",
    countryName: "United Kingdom",
    currencyISOCode: "gbp",
    currencyName: "Pound sterling",
    region: "Main",
    isChecked: false,
    firstItem: false,
    moneda: 'Libra esterlina',
    pais: 'Reino Unido',
    zona: 'Main',
  ),
  CountryCurrency(
    countryISOCode: "ar",
    countryName: "Argentina",
    currencyISOCode: "ars",
    currencyName: "Argentine peso",
    region: "Latin America",
    isChecked: false,
    firstItem: true,
    moneda: 'Peso argentino',
    pais: 'Argentina',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "ra_dso",
    countryName: "Argentina",
    currencyISOCode: "ra_dso",
    currencyName: "Argentine peso: Solidario Rate",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Peso argentino: Dólar Solidario',
    pais: 'Argentina',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "ra_dta",
    countryName: "Argentina",
    currencyISOCode: "ra_dta",
    currencyName: "Argentine peso: Tarjeta Rate",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Peso argentino: Dólar Tarjeta',
    pais: 'Argentina',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "ra_dqa",
    countryName: "Argentina",
    currencyISOCode: "ra_dqa",
    currencyName: "Argentine peso: Qatar Rate",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Peso argentino: Dólar Qatar',
    pais: 'Argentina',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "ra_dne",
    countryName: "Argentina",
    currencyISOCode: "ra_dne",
    currencyName: "Argentine peso: Netflix Rate",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Peso argentino: Dólar Netflix',
    pais: 'Argentina',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "ra_mep",
    countryName: "Argentina",
    currencyISOCode: "ra_mep",
    currencyName: "Argentine peso: Bolsa MEP Rate",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Peso argentino: Dólar Bolsa MEP',
    pais: 'Argentina',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "ra_ccl",
    countryName: "Argentina",
    currencyISOCode: "ra_ccl",
    currencyName: "Argentine peso: CCL Rate",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Peso argentino: Dólar CCL',
    pais: 'Argentina',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "bo",
    countryName: "Bolivia",
    currencyISOCode: "bob",
    currencyName: "Boliviano",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Boliviano',
    pais: 'Bolivia',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "br",
    countryName: "Brazil",
    currencyISOCode: "brl",
    currencyName: "Brazilian real",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Real brasileño',
    pais: 'Brasil',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "cl",
    countryName: "Chile",
    currencyISOCode: "clp",
    currencyName: "Chilean peso",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Peso chileno',
    pais: 'Chile',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "co",
    countryName: "Colombia",
    currencyISOCode: "cop",
    currencyName: "Colombian peso",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Peso colombiano',
    pais: 'Colombia',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "cr",
    countryName: "Costa Rica",
    currencyISOCode: "crc",
    currencyName: "Costa Rican colon",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Colón costarricense',
    pais: 'Costa Rica',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "cu",
    countryName: "Cuba",
    currencyISOCode: "cup",
    currencyName: "Cuban peso",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Peso cubano',
    pais: 'Cuba',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "do",
    countryName: "Dominican Republic",
    currencyISOCode: "dop",
    currencyName: "Dominican peso",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Peso dominicano',
    pais: 'República Dominicana',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "ec",
    countryName: "Ecuador",
    currencyISOCode: "usd",
    currencyName: "US dollar",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar estadounidense',
    pais: 'Ecuador',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "sv",
    countryName: "El Salvador",
    currencyISOCode: "usd",
    currencyName: "US dollar",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar estadounidense',
    pais: 'El Salvador',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "gt",
    countryName: "Guatemala",
    currencyISOCode: "gtq",
    currencyName: "Quetzal",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Quetzal',
    pais: 'Guatemala',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "hn",
    countryName: "Honduras",
    currencyISOCode: "hnl",
    currencyName: "Lempira",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Lempira',
    pais: 'Honduras',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "mx",
    countryName: "Mexico",
    currencyISOCode: "mxn",
    currencyName: "Mexican peso",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Peso mexicano',
    pais: 'México',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "ni",
    countryName: "Nicaragua",
    currencyISOCode: "nio",
    currencyName: "Nicaraguan córdoba",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Córdoba nicaragüense',
    pais: 'Nicaragua',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "pa",
    countryName: "Panama",
    currencyISOCode: "usd",
    currencyName: "US dollar",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar estadounidense',
    pais: 'Panama',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "py",
    countryName: "Paraguay",
    currencyISOCode: "pyg",
    currencyName: "Paraguayan guaraní",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Guaraní',
    pais: 'Paraguay',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "pe",
    countryName: "Peru",
    currencyISOCode: "pen",
    currencyName: "Peruvian sol",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Sol',
    pais: 'Perú',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "pr",
    countryName: "Puerto Rico",
    currencyISOCode: "usd",
    currencyName: "US dollar",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar estadounidense',
    pais: 'Puerto Rico',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "uy",
    countryName: "Uruguay",
    currencyISOCode: "uyu",
    currencyName: "Uruguayan peso",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Peso uruguayo',
    pais: 'Uruguay',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "ve",
    countryName: "Venezuela",
    currencyISOCode: "ves",
    currencyName: "Venezuelan bolívar",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
    moneda: 'Bolívar',
    pais: 'Venezuela',
    zona: 'Latinoamérica',
  ),
  CountryCurrency(
    countryISOCode: "ai",
    countryName: "Anguilla",
    currencyISOCode: "xcd",
    currencyName: "East Caribbean dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: true,
    moneda: 'Dólar del caribe oriental',
    pais: 'Anguila',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "ag",
    countryName: "Antigua and Barbuda",
    currencyISOCode: "xcd",
    currencyName: "East Caribbean dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar del caribe oriental',
    pais: 'Antigua y Barbuda',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "aw",
    countryName: "Aruba",
    currencyISOCode: "awg",
    currencyName: "Aruban Florin",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Florín arubeño',
    pais: 'Aruba',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "bs",
    countryName: "Bahamas",
    currencyISOCode: "bsd",
    currencyName: "Bahamian dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar bahameño',
    pais: 'Bahamas',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "bb",
    countryName: "Barbados",
    currencyISOCode: "bbd",
    currencyName: "Barbados dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar de Barbados',
    pais: 'Barbados',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "bz",
    countryName: "Belize",
    currencyISOCode: "bzd",
    currencyName: "Belize dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar de Belice',
    pais: 'Belice',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "bm",
    countryName: "Bermuda",
    currencyISOCode: "bmd",
    currencyName: "Bermudian dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'dólar bermudeño',
    pais: 'Bermudas',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "bq",
    countryName: "Bonaire, Sint Eustatius and Saba",
    currencyISOCode: "usd",
    currencyName: "US dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar estadounidense',
    pais: 'Bonaire, San Eustaquio y Saba',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "ky",
    countryName: "Cayman Islands",
    currencyISOCode: "kyd",
    currencyName: "Cayman Islands dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar de las Islas Caimán',
    pais: 'Islas Caimán',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "cw",
    countryName: "Curaçao",
    currencyISOCode: "ang",
    currencyName: "Netherlands Antillean guilder",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Florín antillano neerlandés',
    pais: 'Curazao',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "dm",
    countryName: "Dominica",
    currencyISOCode: "xcd",
    currencyName: "East Caribbean dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar del caribe oriental',
    pais: 'Dominica',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "gf",
    countryName: "French Guiana",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Guayana Francesa',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "gd",
    countryName: "Grenada",
    currencyISOCode: "xcd",
    currencyName: "East Caribbean dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar del caribe oriental',
    pais: 'Granada',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "gp",
    countryName: "Guadeloupe",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Guadalupe',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "gy",
    countryName: "Guyana",
    currencyISOCode: "gyd",
    currencyName: "Guyana dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar guyanés',
    pais: 'Guyana',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "ht",
    countryName: "Haiti",
    currencyISOCode: "htg",
    currencyName: "Gourde",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Gourde',
    pais: 'Haití',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "jm",
    countryName: "Jamaica",
    currencyISOCode: "jmd",
    currencyName: "Jamaican dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar jamaiquino',
    pais: 'Jamaica',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "mq",
    countryName: "Martinique",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Martinica',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "ms",
    countryName: "Montserrat",
    currencyISOCode: "xcd",
    currencyName: "East Caribbean dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar del caribe oriental',
    pais: 'Montserrat',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "bl",
    countryName: "Saint Barthélemy",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'San Bartolomé',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "kn",
    countryName: "Saint Kitts and Nevis",
    currencyISOCode: "xcd",
    currencyName: "East Caribbean dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar del caribe oriental',
    pais: 'San Cristóbal y Nieves',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "lc",
    countryName: "Saint Lucia",
    currencyISOCode: "xcd",
    currencyName: "East Caribbean dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar del caribe oriental',
    pais: 'Santa Lucía',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "mf",
    countryName: "Saint Martin",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'San Martín (FR)',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "vc",
    countryName: "Saint Vincent and the Grenadines",
    currencyISOCode: "xcd",
    currencyName: "East Caribbean dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar del caribe oriental',
    pais: 'San Vicente y las Granadinas',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "sx",
    countryName: "Sint Maarten",
    currencyISOCode: "ang",
    currencyName: "Netherlands Antillean guilder",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Florín antillano neerlandés',
    pais: 'San Martín (NL)',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "sr",
    countryName: "Suriname",
    currencyISOCode: "srd",
    currencyName: "Surinam dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar de Surinam',
    pais: 'Surinam',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "tt",
    countryName: "Trinidad and Tobago",
    currencyISOCode: "ttd",
    currencyName: "Trinidad and Tobago dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar de Trinidad y Tobago',
    pais: 'Trinidad y Tobago',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "tc",
    countryName: "Turks and Caicos Islands",
    currencyISOCode: "usd",
    currencyName: "US dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar estadounidense',
    pais: 'Islas Turcas y Caicos',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "vg",
    countryName: "British Virgin Islands",
    currencyISOCode: "usd",
    currencyName: "US dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar estadounidense',
    pais: 'Islas Vírgenes Británicas',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "vi",
    countryName: "Virgin Islands, U.S.",
    currencyISOCode: "usd",
    currencyName: "US dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar estadounidense',
    pais: 'Islas Vírgenes de los Estados Unidos',
    zona: 'Caribe',
  ),
  CountryCurrency(
    countryISOCode: "ax",
    countryName: "Aland Islands",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: true,
    moneda: 'Euro',
    pais: 'Islas Aland',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "al",
    countryName: "Albania",
    currencyISOCode: "all",
    currencyName: "Lek",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Lek',
    pais: 'Albania',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "ad",
    countryName: "Andorra",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Andorra',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "am",
    countryName: "Armenia",
    currencyISOCode: "amd",
    currencyName: "Armenian dram",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Dram armenio',
    pais: 'Armenia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "at",
    countryName: "Austria",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Austria',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "by",
    countryName: "Belarus",
    currencyISOCode: "byn",
    currencyName: "Belarusian Ruble",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'rublo bielorruso',
    pais: 'Bielorrusia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "be",
    countryName: "Belgium",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Bélgica',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "ba",
    countryName: "Bosnia and Herzegovina",
    currencyISOCode: "bam",
    currencyName: "Convertible Mark",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Marco bosnioherzegovino',
    pais: 'Bosnia y Herzegovina',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "bv",
    countryName: "Bouvet Island",
    currencyISOCode: "nok",
    currencyName: "Norwegian Krone",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Corona noruega',
    pais: 'Isla Bouvet',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "bg",
    countryName: "Bulgaria",
    currencyISOCode: "bgn",
    currencyName: "Bulgarian Lev",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Lev búlgaro',
    pais: 'Bulgaria',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "hr",
    countryName: "Croatia",
    currencyISOCode: "hrk",
    currencyName: "Croatian kuna",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Kuna croata',
    pais: 'Croacia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "cy",
    countryName: "Cyprus",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Chipre',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "cz",
    countryName: "Czechia",
    currencyISOCode: "czk",
    currencyName: "Czech Koruna",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Corona checa',
    pais: 'Chequia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "dk",
    countryName: "Denmark",
    currencyISOCode: "dkk",
    currencyName: "Danish Krone",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Corona danesa',
    pais: 'Dinamarca',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "ee",
    countryName: "Estonia",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Estonia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "fo",
    countryName: "Faroe Islands",
    currencyISOCode: "dkk",
    currencyName: "Danish Krone",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Corona danesa',
    pais: 'Islas Faroe',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "fi",
    countryName: "Finland",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Finlandia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "fr",
    countryName: "France",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Francia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "ge",
    countryName: "Georgia",
    currencyISOCode: "gel",
    currencyName: "Lari",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Lari',
    pais: 'Georgia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "de",
    countryName: "Germany",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Alemania',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "gr",
    countryName: "Greece",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Grecia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "gl",
    countryName: "Greenland",
    currencyISOCode: "dkk",
    currencyName: "Danish Krone",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Corona danesa',
    pais: 'Groenlandia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "gg",
    countryName: "Guernsey",
    currencyISOCode: "gbp",
    currencyName: "Pound Sterling",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Libra esterlina',
    pais: 'Guernsey',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "hu",
    countryName: "Hungary",
    currencyISOCode: "huf",
    currencyName: "Forint",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Forint',
    pais: 'Hungría',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "is",
    countryName: "Iceland",
    currencyISOCode: "isk",
    currencyName: "Iceland krona",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Corona islandesa',
    pais: 'Islandia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "ie",
    countryName: "Ireland",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Irlanda',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "im",
    countryName: "Isle of Man",
    currencyISOCode: "gbp",
    currencyName: "Pound Sterling",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Libra esterlina',
    pais: 'Isla de Man',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "it",
    countryName: "Italy",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Italia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "je",
    countryName: "Jersey",
    currencyISOCode: "gbp",
    currencyName: "Pound Sterling",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Libra esterlina',
    pais: 'Jersey',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "lv",
    countryName: "Latvia",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Letonia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "li",
    countryName: "Liechtenstein",
    currencyISOCode: "chf",
    currencyName: "Swiss Franc",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco suizo',
    pais: 'Liechtenstein',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "lt",
    countryName: "Lithuania",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Lituania',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "lu",
    countryName: "Luxembourg",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Luxemburgo',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "mt",
    countryName: "Malta",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Malta',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "md",
    countryName: "Moldova",
    currencyISOCode: "mdl",
    currencyName: "Moldovan Leu",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Leu moldavo',
    pais: 'Moldavia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "mc",
    countryName: "Monaco",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Mónaco',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "me",
    countryName: "Montenegro",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Montenegro',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "nl",
    countryName: "Netherlands",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Países Bajos',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "mk",
    countryName: "North Macedonia",
    currencyISOCode: "mkd",
    currencyName: "Denar",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Denar macedonio',
    pais: 'Macedonia del Norte',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "no",
    countryName: "Norway",
    currencyISOCode: "nok",
    currencyName: "Norwegian Krone",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Corona noruega',
    pais: 'Noruega',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "pl",
    countryName: "Poland",
    currencyISOCode: "pln",
    currencyName: "Zloty",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Zloty',
    pais: 'Polonia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "pt",
    countryName: "Portugal",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Portugal',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "ro",
    countryName: "Romania",
    currencyISOCode: "ron",
    currencyName: "Romanian Leu",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Leu rumano',
    pais: 'Rumania',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "ru",
    countryName: "Russia",
    currencyISOCode: "rub",
    currencyName: "Russian Ruble",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Rublo ruso',
    pais: 'Rusia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "pm",
    countryName: "Saint Pierre and Miquelon",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'San Pedro y Miquelón',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "sm",
    countryName: "San Marino",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'San Marino',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "rs",
    countryName: "Serbia",
    currencyISOCode: "rsd",
    currencyName: "Serbian Dinar",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Dinar serbio',
    pais: 'Serbia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "sk",
    countryName: "Slovakia",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Eslovaquia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "si",
    countryName: "Slovenia",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Eslovenia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "es",
    countryName: "Spain",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'España',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "sj",
    countryName: "Svalbard and Jan Mayen",
    currencyISOCode: "nok",
    currencyName: "Norwegian Krone",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Corona noruega',
    pais: 'Svalbard y Jan Mayen',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "se",
    countryName: "Sweden",
    currencyISOCode: "sek",
    currencyName: "Swedish Krona",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Corona sueca',
    pais: 'Suecia',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "ch",
    countryName: "Switzerland",
    currencyISOCode: "chf",
    currencyName: "Swiss Franc",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco suizo',
    pais: 'Suiza',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "ua",
    countryName: "Ukraine",
    currencyISOCode: "uah",
    currencyName: "Hryvnia",
    region: "Europe",
    isChecked: false,
    firstItem: false,
    moneda: 'Grivna',
    pais: 'Ucrania',
    zona: 'Europa',
  ),
  CountryCurrency(
    countryISOCode: "af",
    countryName: "Afghanistan",
    currencyISOCode: "afn",
    currencyName: "Afghani",
    region: "Middle East",
    isChecked: false,
    firstItem: true,
    moneda: 'Afgani',
    pais: 'Afganistán',
    zona: 'Oriente Medio',
  ),
  CountryCurrency(
    countryISOCode: "bh",
    countryName: "Bahrain",
    currencyISOCode: "bhd",
    currencyName: "Bahraini Dinar",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
    moneda: 'Dinar bahreiní',
    pais: 'Baréin',
    zona: 'Oriente Medio',
  ),
  CountryCurrency(
    countryISOCode: "ir",
    countryName: "Iran",
    currencyISOCode: "irr",
    currencyName: "Iranian rial",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
    moneda: 'Rial iraní',
    pais: 'Irán',
    zona: 'Oriente Medio',
  ),
  CountryCurrency(
    countryISOCode: "iq",
    countryName: "Iraq",
    currencyISOCode: "iqd",
    currencyName: "Iraqi dinar",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
    moneda: 'Dinar iraquí',
    pais: 'Irak',
    zona: 'Oriente Medio',
  ),
  CountryCurrency(
    countryISOCode: "il",
    countryName: "Israel",
    currencyISOCode: "ils",
    currencyName: "Israeli new shekel",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
    moneda: 'Nuevo séquel',
    pais: 'Israel',
    zona: 'Oriente Medio',
  ),
  CountryCurrency(
    countryISOCode: "jo",
    countryName: "Jordan",
    currencyISOCode: "jod",
    currencyName: "Jordanian dinar",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
    moneda: 'Dinar jordano',
    pais: 'Jordán',
    zona: 'Oriente Medio',
  ),
  CountryCurrency(
    countryISOCode: "kw",
    countryName: "Kuwait",
    currencyISOCode: "kwd",
    currencyName: "Kuwaiti dinar",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
    moneda: 'Dinar kuwaití',
    pais: 'Kuwait',
    zona: 'Oriente Medio',
  ),
  CountryCurrency(
    countryISOCode: "lb",
    countryName: "Lebanon",
    currencyISOCode: "lbp",
    currencyName: "Lebanese pound",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
    moneda: 'Libra libanesa',
    pais: 'Líbano',
    zona: 'Oriente Medio',
  ),
  CountryCurrency(
    countryISOCode: "om",
    countryName: "Oman",
    currencyISOCode: "omr",
    currencyName: "Rial omani",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
    moneda: 'Rial omaní',
    pais: 'Omán',
    zona: 'Oriente Medio',
  ),
  CountryCurrency(
    countryISOCode: "pk",
    countryName: "Pakistan",
    currencyISOCode: "pkr",
    currencyName: "Pakistan rupee",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
    moneda: 'Rupia de Pakistán',
    pais: 'Pakistán',
    zona: 'Oriente Medio',
  ),
  CountryCurrency(
    countryISOCode: "qa",
    countryName: "Qatar",
    currencyISOCode: "qar",
    currencyName: "Qatari rial",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
    moneda: 'Rial qatarí',
    pais: 'Catar',
    zona: 'Oriente Medio',
  ),
  CountryCurrency(
    countryISOCode: "sa",
    countryName: "Saudi Arabia",
    currencyISOCode: "sar",
    currencyName: "Saudi riyal",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
    moneda: 'Rial saudita',
    pais: 'Arabia Saudita',
    zona: 'Oriente Medio',
  ),
  CountryCurrency(
    countryISOCode: "ae",
    countryName: "United Arab Emirates",
    currencyISOCode: "aed",
    currencyName: "UAE rirham",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
    moneda: 'Dírham emiral.',
    pais: 'Emiratos Árabes Unidos',
    zona: 'Oriente Medio',
  ),
  CountryCurrency(
    countryISOCode: "ye",
    countryName: "Yemen",
    currencyISOCode: "yer",
    currencyName: "Yemeni Rial",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
    moneda: 'Rial yemení',
    pais: 'Yemen',
    zona: 'Oriente Medio',
  ),
  CountryCurrency(
    countryISOCode: "az",
    countryName: "Azerbaijan",
    currencyISOCode: "azn",
    currencyName: "Azerbaijan manat",
    region: "Asia",
    isChecked: false,
    firstItem: true,
    moneda: 'Manat azerbaiyano',
    pais: 'Azerbaiyán',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "bd",
    countryName: "Bangladesh",
    currencyISOCode: "bdt",
    currencyName: "Taka",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Taka',
    pais: 'Bangladesh',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "bt",
    countryName: "Bhutan",
    currencyISOCode: "btn",
    currencyName: "Ngultrum",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Ngultrum butanés',
    pais: 'Bután',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "io",
    countryName: "British Indian Ocean Territory",
    currencyISOCode: "usd",
    currencyName: "US dollar",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar estadounidense',
    pais: 'Territorio Británico del Océano Índico',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "bn",
    countryName: "Brunei Darussalam",
    currencyISOCode: "bnd",
    currencyName: "Brunei dollar",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar de Brunéi',
    pais: 'Brunei Darussalam',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "kh",
    countryName: "Cambodia",
    currencyISOCode: "khr",
    currencyName: "Riel",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Riel camboyano',
    pais: 'Camboya',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "cn",
    countryName: "China",
    currencyISOCode: "cny",
    currencyName: "Yuan Renminbi",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Yuan Renminbi',
    pais: 'China',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "hk",
    countryName: "Hong Kong",
    currencyISOCode: "hkd",
    currencyName: "Hong Kong dollar",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar de Hong Kong',
    pais: 'Hong Kong',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "in",
    countryName: "India",
    currencyISOCode: "inr",
    currencyName: "Indian Rupee",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Rupia india',
    pais: 'India',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "id",
    countryName: "Indonesia",
    currencyISOCode: "idr",
    currencyName: "Indonesian rupiah",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Rupia indonesia',
    pais: 'Indonesia',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "jp",
    countryName: "Japan",
    currencyISOCode: "jpy",
    currencyName: "Yen",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Yen',
    pais: 'Japón',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "kz",
    countryName: "Kazakstan",
    currencyISOCode: "kzt",
    currencyName: "Tenge",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Tenge kazajo',
    pais: 'Kazajstán',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "kr",
    countryName: "Korea",
    currencyISOCode: "krw",
    currencyName: "South Korean won",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Won surcoreano',
    pais: 'Corea',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "kg",
    countryName: "Kyrgyzstan",
    currencyISOCode: "kgs",
    currencyName: "Som",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Som kirguís',
    pais: 'Kirguistán',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "la",
    countryName: "Laos",
    currencyISOCode: "lak",
    currencyName: "Lao Kip",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Kip laosiano',
    pais: 'Laos',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "mo",
    countryName: "Macao",
    currencyISOCode: "mop",
    currencyName: "Pataca",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Pataca',
    pais: 'Macao',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "my",
    countryName: "Malaysia",
    currencyISOCode: "myr",
    currencyName: "Malaysian ringgit",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Ringgit',
    pais: 'Malasia',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "mv",
    countryName: "Maldives",
    currencyISOCode: "mvr",
    currencyName: "Maldivian rufiyaa",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Rupia de Maldivas',
    pais: 'Maldivas',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "mm",
    countryName: "Myanmar",
    currencyISOCode: "mmk",
    currencyName: "Kyat",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Kyat birmano',
    pais: 'Birmania',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "np",
    countryName: "Nepal",
    currencyISOCode: "npr",
    currencyName: "Nepalese rupee",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Rupia nepalí',
    pais: 'Nepal',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "ph",
    countryName: "Philippines",
    currencyISOCode: "php",
    currencyName: "Philippine peso",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Peso filipino',
    pais: 'Filipinas',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "sg",
    countryName: "Singapore",
    currencyISOCode: "sgd",
    currencyName: "Singapore dollar",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar de Singapur',
    pais: 'Singapur',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "lk",
    countryName: "Sri Lanka",
    currencyISOCode: "lkr",
    currencyName: "Sri Lanka Rupee",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Rupia de Sri Lanka',
    pais: 'Sri Lanka',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "tw",
    countryName: "Taiwan",
    currencyISOCode: "twd",
    currencyName: "New Taiwan dollar",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Nuevo dólar taiwanés',
    pais: 'Taiwán',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "tj",
    countryName: "Tajikistan",
    currencyISOCode: "tjs",
    currencyName: "Somoni",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Somoni tayiko',
    pais: 'Tayikistán',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "th",
    countryName: "Thailand",
    currencyISOCode: "thb",
    currencyName: "Baht",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Baht tailandés',
    pais: 'Tailandia',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "tl",
    countryName: "Timor-Leste",
    currencyISOCode: "usd",
    currencyName: "US dollar",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar estadounidense',
    pais: 'Timor Oriental',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "tr",
    countryName: "Türkiye",
    currencyISOCode: "try",
    currencyName: "Turkish Lira",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Lira turca',
    pais: 'Turquía',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "tm",
    countryName: "Turkmenistan",
    currencyISOCode: "tmt",
    currencyName: "Turkmenistani manat",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Manat turcomano',
    pais: 'Turkmenistán',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "uz",
    countryName: "Uzbekistan",
    currencyISOCode: "uzs",
    currencyName: "Uzbekistan sum",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Som uzbeko',
    pais: 'Uzbekistán',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "vn",
    countryName: "Vietnam",
    currencyISOCode: "vnd",
    currencyName: "Dong",
    region: "Asia",
    isChecked: false,
    firstItem: false,
    moneda: 'Dong',
    pais: 'Vietnam',
    zona: 'Asia',
  ),
  CountryCurrency(
    countryISOCode: "dz",
    countryName: "Algeria",
    currencyISOCode: "dzd",
    currencyName: "Algerian dinar",
    region: "Africa",
    isChecked: false,
    firstItem: true,
    moneda: 'Dinar argelino',
    pais: 'Argelia',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "ao",
    countryName: "Angola",
    currencyISOCode: "aoa",
    currencyName: "Kwanza",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Kwanza angoleño',
    pais: 'Angola',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "bj",
    countryName: "Benin",
    currencyISOCode: "xof",
    currencyName: "West African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco CFA de África Occidental',
    pais: 'Benín',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "bw",
    countryName: "Botswana",
    currencyISOCode: "bwp",
    currencyName: "Pula",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Pula',
    pais: 'Botsuana',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "bf",
    countryName: "Burkina Faso",
    currencyISOCode: "xof",
    currencyName: "West African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco CFA de África Occidental',
    pais: 'Burkina Faso',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "bi",
    countryName: "Burundi",
    currencyISOCode: "bif",
    currencyName: "Burundi franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco de Burundi',
    pais: 'Burundi',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "cm",
    countryName: "Cameroon",
    currencyISOCode: "xaf",
    currencyName: "Central African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco CFA de África Central',
    pais: 'Camerún',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "cv",
    countryName: "Cape Verde",
    currencyISOCode: "cve",
    currencyName: "Cape Verdean escudo",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Escudo caboverdiano',
    pais: 'Cabo Verde',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "cf",
    countryName: "Central African Republic",
    currencyISOCode: "xaf",
    currencyName: "Central African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco CFA de África Central',
    pais: 'República Centroafricana',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "td",
    countryName: "Chad",
    currencyISOCode: "xaf",
    currencyName: "Central African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco CFA de África Central',
    pais: 'Chad',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "km",
    countryName: "Comoros",
    currencyISOCode: "kmf",
    currencyName: "Comorian franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco comorano',
    pais: 'Comoras',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "cg",
    countryName: "Congo",
    currencyISOCode: "xaf",
    currencyName: "Central African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco CFA de África Central',
    pais: 'Congo',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "cd",
    countryName: "Congo (DR)",
    currencyISOCode: "cdf",
    currencyName: "Congolese franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco congoleño',
    pais: 'Congo (RD)',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "ci",
    countryName: "Ivory Coast",
    currencyISOCode: "xof",
    currencyName: "West African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco CFA de África Occidental',
    pais: 'Costa de Marfil',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "dj",
    countryName: "Djibouti",
    currencyISOCode: "djf",
    currencyName: "Djibouti franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco yibutiano',
    pais: 'Yibuti',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "eg",
    countryName: "Egypt",
    currencyISOCode: "egp",
    currencyName: "Egyptian pound",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Libra egipcia',
    pais: 'Egipto',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "gq",
    countryName: "Equatorial Guinea",
    currencyISOCode: "xaf",
    currencyName: "Central African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco CFA de África Central',
    pais: 'Guinea Ecuatorial',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "sz",
    countryName: "Eswatini",
    currencyISOCode: "szl",
    currencyName: "Lilangeni",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Lilangeni',
    pais: 'Eswatini',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "et",
    countryName: "Ethiopia",
    currencyISOCode: "etb",
    currencyName: "Ethiopian birr",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Birr etíope',
    pais: 'Etiopía',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "tf",
    countryName: "French Southern Territories",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Territorios Franceses del Sur',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "ga",
    countryName: "Gabon",
    currencyISOCode: "xaf",
    currencyName: "Central African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco CFA de África Central',
    pais: 'Gabón',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "gm",
    countryName: "Gambia",
    currencyISOCode: "gmd",
    currencyName: "Dalasi",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Dalasi',
    pais: 'Gambia',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "gh",
    countryName: "Ghana",
    currencyISOCode: "ghs",
    currencyName: "Ghana cedi",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Cedi',
    pais: 'Ghana',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "gn",
    countryName: "Guinea",
    currencyISOCode: "gnf",
    currencyName: "Guinean franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco guineano',
    pais: 'Guinea',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "gw",
    countryName: "Guinea-Bissau",
    currencyISOCode: "xof",
    currencyName: "West African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco CFA de África Occidental',
    pais: 'Guinea-Bisáu',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "ke",
    countryName: "Kenya",
    currencyISOCode: "kes",
    currencyName: "Kenyan shilling",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Chelín keniano',
    pais: 'Kenia',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "ls",
    countryName: "Lesotho",
    currencyISOCode: "lsl",
    currencyName: "Loti",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Loti',
    pais: 'Lesoto',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "lr",
    countryName: "Liberia",
    currencyISOCode: "lrd",
    currencyName: "Liberian dollar",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar liberiano',
    pais: 'Liberia',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "ly",
    countryName: "Libya",
    currencyISOCode: "lyd",
    currencyName: "Libyan dinar",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Dinar libio',
    pais: 'Libia',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "mg",
    countryName: "Madagascar",
    currencyISOCode: "mga",
    currencyName: "Malagasy ariary",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Ariary malgache',
    pais: 'Madagascar',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "mw",
    countryName: "Malawi",
    currencyISOCode: "mwk",
    currencyName: "Malawi kwacha",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Kwacha malauí',
    pais: 'Malaui',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "ml",
    countryName: "Mali",
    currencyISOCode: "xof",
    currencyName: "West African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco CFA de África Occidental',
    pais: 'Malí',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "mr",
    countryName: "Mauritania",
    currencyISOCode: "mru",
    currencyName: "Ouguiya",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Uguiya',
    pais: 'Mauritania',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "mu",
    countryName: "Mauritius",
    currencyISOCode: "mur",
    currencyName: "Mauritius rupee",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Rupia de Mauricio',
    pais: 'Mauricio',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "yt",
    countryName: "Mayotte",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'Mayotte',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "ma",
    countryName: "Morocco",
    currencyISOCode: "mad",
    currencyName: "Moroccan dirham",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Dírham marroquí',
    pais: 'Marruecos',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "mz",
    countryName: "Mozambique",
    currencyISOCode: "mzn",
    currencyName: "Mozambique metical",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Metical mozambiqueño',
    pais: 'Mozambique',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "na",
    countryName: "Namibia",
    currencyISOCode: "nad",
    currencyName: "Namibia dollar",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar namibio',
    pais: 'Namibia',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "ne",
    countryName: "Niger",
    currencyISOCode: "xof",
    currencyName: "West African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco CFA de África Occidental',
    pais: 'Níger',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "ng",
    countryName: "Nigeria",
    currencyISOCode: "ngn",
    currencyName: "Naira",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Naira',
    pais: 'Nigeria',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "re",
    countryName: "Reunion",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Euro',
    pais: 'La Reunión',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "rw",
    countryName: "Rwanda",
    currencyISOCode: "rwf",
    currencyName: "Rwanda franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco ruandés',
    pais: 'Ruanda',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "sn",
    countryName: "Senegal",
    currencyISOCode: "xof",
    currencyName: "West African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco CFA de África Occidental',
    pais: 'Senegal',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "sc",
    countryName: "Seychelles",
    currencyISOCode: "scr",
    currencyName: "Seychelles rupee",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Rupia de Seychelles',
    pais: 'Seychelles',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "sl",
    countryName: "Sierra Leone",
    currencyISOCode: "sll",
    currencyName: "Leone",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Leone',
    pais: 'Sierra Leona',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "so",
    countryName: "Somalia",
    currencyISOCode: "sos",
    currencyName: "Somali shilling",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Chelín somalí',
    pais: 'Somalia',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "za",
    countryName: "South Africa",
    currencyISOCode: "zar",
    currencyName: "Rand",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Rand',
    pais: 'Sudáfrica',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "sd",
    countryName: "Sudan",
    currencyISOCode: "sdg",
    currencyName: "Sudanese pound",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Libra sudanesa',
    pais: 'Sudán',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "tz",
    countryName: "Tanzania",
    currencyISOCode: "tzs",
    currencyName: "Tanzanian shilling",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Chelín tanzano',
    pais: 'Tanzania',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "tg",
    countryName: "Togo",
    currencyISOCode: "xof",
    currencyName: "West African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco CFA de África Occidental',
    pais: 'Togo',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "tn",
    countryName: "Tunisia",
    currencyISOCode: "tnd",
    currencyName: "Tunisian dinar",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Dinar tunecino',
    pais: 'Túnez',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "ug",
    countryName: "Uganda",
    currencyISOCode: "ugx",
    currencyName: "Uganda shilling",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Chelín ugandés',
    pais: 'Uganda',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "eh",
    countryName: "Western Sahara",
    currencyISOCode: "mad",
    currencyName: "Moroccan dirham",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Dírham marroquí',
    pais: 'Sahara Occidental',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "zm",
    countryName: "Zambia",
    currencyISOCode: "zmw",
    currencyName: "Zambian kwacha",
    region: "Africa",
    isChecked: false,
    firstItem: false,
    moneda: 'Kwacha zambiano',
    pais: 'Zambia',
    zona: 'África',
  ),
  CountryCurrency(
    countryISOCode: "as",
    countryName: "American Samoa",
    currencyISOCode: "usd",
    currencyName: "US dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: true,
    moneda: 'Dólar estadounidense',
    pais: 'Samoa Americana',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "au",
    countryName: "Australia",
    currencyISOCode: "aud",
    currencyName: "Australian dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar australiano',
    pais: 'Australia',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "cx",
    countryName: "Christmas Island",
    currencyISOCode: "aud",
    currencyName: "Australian dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar australiano',
    pais: 'Isla de Navidad',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "cc",
    countryName: "Cocos (Keeling) Islands",
    currencyISOCode: "aud",
    currencyName: "Australian dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar australiano',
    pais: 'Islas Cocos',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "ck",
    countryName: "Cook Islands",
    currencyISOCode: "nzd",
    currencyName: "New Zealand dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar de Nueva Zelanda',
    pais: 'Islas Cook',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "fj",
    countryName: "Fiji",
    currencyISOCode: "fjd",
    currencyName: "Fiji dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar fiyiano',
    pais: 'Fiyi',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "pf",
    countryName: "French Polynesia",
    currencyISOCode: "xpf",
    currencyName: "CFP Franc",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco CFP',
    pais: 'Polinesia Francesa',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "gu",
    countryName: "Guam",
    currencyISOCode: "usd",
    currencyName: "US dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar estadounidense',
    pais: 'Guam',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "hm",
    countryName: "Heard and Mc Donald Islands",
    currencyISOCode: "aud",
    currencyName: "Australian dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar australiano',
    pais: 'Territorio de las Islas Heard y McDonald',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "ki",
    countryName: "Kiribati",
    currencyISOCode: "aud",
    currencyName: "Australian dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar australiano',
    pais: 'Kiribati',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "mh",
    countryName: "Marshall Islands",
    currencyISOCode: "usd",
    currencyName: "US dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar estadounidense',
    pais: 'Islas Marshall',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "fm",
    countryName: "Micronesia",
    currencyISOCode: "usd",
    currencyName: "US dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar estadounidense',
    pais: 'Micronesia',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "nr",
    countryName: "Nauru",
    currencyISOCode: "aud",
    currencyName: "Australian dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar australiano',
    pais: 'Nauru',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "nc",
    countryName: "New Caledonia",
    currencyISOCode: "xpf",
    currencyName: "CFP Franc",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco CFP',
    pais: 'Nueva Caledonia',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "nz",
    countryName: "New Zealand",
    currencyISOCode: "nzd",
    currencyName: "New Zealand dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar de Nueva Zelanda',
    pais: 'Nueva Zelanda',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "nu",
    countryName: "Niue",
    currencyISOCode: "nzd",
    currencyName: "New Zealand dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar de Nueva Zelanda',
    pais: 'Niue',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "nf",
    countryName: "Norfolk Island",
    currencyISOCode: "aud",
    currencyName: "Australian dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar australiano',
    pais: 'Isla Norfolk',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "mp",
    countryName: "Northern Mariana Islands",
    currencyISOCode: "usd",
    currencyName: "US dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar estadounidense',
    pais: 'Islas Marianas del Norte',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "pw",
    countryName: "Palau",
    currencyISOCode: "usd",
    currencyName: "US dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar estadounidense',
    pais: 'Palaos',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "pg",
    countryName: "Papua New Guinea",
    currencyISOCode: "pgk",
    currencyName: "Kina",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Kina',
    pais: 'Papúa Nueva Guinea',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "pn",
    countryName: "Pitcairn Islands",
    currencyISOCode: "nzd",
    currencyName: "New Zealand dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar de Nueva Zelanda',
    pais: 'Islas Pitcairn',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "sb",
    countryName: "Solomon Islands",
    currencyISOCode: "sbd",
    currencyName: "Solomon Islands dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar de las Islas Salomón',
    pais: 'Islas Salomón',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "tk",
    countryName: "Tokelau",
    currencyISOCode: "nzd",
    currencyName: "New Zealand dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar de Nueva Zelanda',
    pais: 'Tokelau',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "to",
    countryName: "Tonga",
    currencyISOCode: "top",
    currencyName: "Pa’anga",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Pa’anga',
    pais: 'Tonga',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "tv",
    countryName: "Tuvalu",
    currencyISOCode: "aud",
    currencyName: "Australian dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar australiano',
    pais: 'Tuvalu',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "um",
    countryName: "United States Minor Outlying Islands",
    currencyISOCode: "usd",
    currencyName: "US dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Dólar estadounidense',
    pais: 'Islas Ultramarinas Menores de los Estados Unidos',
    zona: 'Oceanía',
  ),
  CountryCurrency(
    countryISOCode: "wf",
    countryName: "Wallis and Futuna",
    currencyISOCode: "xpf",
    currencyName: "CFP Franc",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
    moneda: 'Franco CFP',
    pais: 'Wallis y Futuna',
    zona: 'Oceanía',
  )
];
